Add Redpanda + Upstash to logos
ClickHouse/click-ui pull request #301
Opened 2024-01-08 20:24 UTC by pjhampton

We are making UI changes internally on the control-plane for ClickPipes. This PR adds 2 Kafka protocol provider logos to the UI lib. 

<img width="1508" alt="Screenshot 2024-01-08 at 20 19 23" src="https://github.com/ClickHouse/click-ui/assets/8960296/145a2dd3-889d-4f9e-a4a1-fa4887464794">

---

### Testing

```
$ npm run storybook
```

Navigate to: Icon > Icons > Logos

2024-01-08 20:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/click-ui?pullRequest=301) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/click-ui?pullRequest=301) before we can accept your contribution.<br/><hr/>**Pete Hampton** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/click-ui?pullRequest=301) it.</sub>

2024-01-08 20:37 UTC, vineethasok requested changes

2024-01-08 20:37 UTC, vineethasok commented on src/components/Logos/Upstash.tsx
> +        <path d="M256,42.415426 C199.445737,-14.1384753 107.753322,-14.1384753 51.1994207,42.415426 C-5.35485714,98.9696894 -5.35485714,190.662104 51.1994207,247.216367 L76.7989048,221.616521 C34.384
Need to change fill-opacity to fillOpacity

2024-01-09 01:08 UTC, serdec approved these changes

2024-01-09 02:06 UTC, gjones commented on src/components/Logos/Redpanda.tsx
> +    width="161"
This should be 64px in width an height, the view box should match.

2024-01-09 02:06 UTC, gjones commented on src/components/Logos/Upstash.tsx
> +    viewBox="0 0 256 341"
Same here

2024-01-09 02:26 UTC, gjones commented
Hiya @pjhampton, thanks for the PR! 🎉  All looks good except the svgs themselves. I've attached correct sized versions below. Hope that helps!

[Logos.zip](https://github.com/ClickHouse/click-ui/files/13868044/Logos.zip)

2024-01-09 10:53 UTC, pjhampton commented
Thanks, everyone! I also added AWS Kinesis to save us some time in the near future.

2024-01-09 15:09 UTC, vineethasok approved these changes

2024-01-09 15:10 UTC, merged