Add CheckboxMultiSelect
ClickHouse/click-ui pull request #389
Opened 2024-04-02 20:42 UTC by hoorayimhelping

Closes https://github.com/ClickHouse/control-plane/issues/7993

- Adds `CheckboxMultiSelect`, a multi select component that shows selected items inline with a checkbox, rather than the typical label cloud of `MultiSelect`

<img width="1624" alt="Screenshot 2024-04-02 at 4 33 51 PM" src="https://github.com/ClickHouse/click-ui/assets/146112/76359e53-070c-4325-b05b-4105e5bfc3d0">

2024-04-04 09:30 UTC, vineethasok requested changes
@gjones @crisalbu  Is this a new design?
Would we be showing the left Icon before the checkbox or after

2024-04-04 10:54 UTC, crisalbu commented
First time I see this, but https://github.com/ClickHouse/control-plane/issues/7993 specifies that this was discussed with @gjones 

To @vineethasok's point, the icon should go after the checkbox. All checkboxes should be left aligned.

2024-04-04 12:07 UTC, gjones commented
> To @vineethasok's point, the icon should go after the checkbox. All checkboxes should be left aligned.

Correct, in reality we'd be very unlikely to use them together.

2024-04-10 16:35 UTC, vineethasok approved these changes

2024-04-10 19:23 UTC, merged